// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bopxfprnrnzvdkvadurp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvcHhmcHJucm56dmRrdmFkdXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NTA5ODYsImV4cCI6MjA2MTEyNjk4Nn0.Hkg6Qhva5wghoxquKYylbgDmNi05XpfH1ZBhtG68M6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);